# ============================================
# $Id: Makefile,v 1.1 2007/08/16 09:46:21 yannick Exp $
# ============================================


export targetdir
export utildir

#SUBDIR= Users


include $(utildir)/PubRule


DISTFILES+=changelog changelog.in compat control copyright dirs postinst rules 
