# ============================================
# $Id: Makefile,v 1.1 2007/01/25 17:54:38 eric Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(shell basename `pwd` | tr [a-z] [A-Z])

export appname


include $(utildir)/PubRule



